language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r your-community *
  - mkdir -p deploy
  - mv your-community.zip deploy/your-community.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: daangn-price-api-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: hihiboss/your-community
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: daangn-price-api-deploy
    key: your-community.zip
    bundle_type: zip
    application: daangn-price-api
    deployment_group: daangn-price-api-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: hihiboss/your-community
      branch: master